name: SCA (Node + Go)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  sca:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------- NODE SCA ----------
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run npm audit (fail on high+)
        working-directory: ./frontend
        run: npm audit --audit-level=high

      # ---------- GO SCA ----------
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.5'

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run govulncheck
        working-directory: ./backend
        env:
          PATH: $HOME/go/bin:${{ env.PATH }}
        run: govulncheck ./...
